"""add user_id to app_notifications

Revision ID: 38ea6523f258
Revises: 88791d39742e
Create Date: 2026-06-29 11:58:11.242287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ea6523f258'
down_revision: Union[str, Sequence[str], None] = '88791d39742e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_notifications', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index('ix_app_notifications_user_id', 'app_notifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'app_notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_notifications', type_='foreignkey')
    op.drop_index('ix_app_notifications_user_id', table_name='app_notifications')
    op.drop_column('app_notifications', 'user_id')
    # ### end Alembic commands ###
